services:

  liquibase:
    container_name:  maven_proj_liquibase
    image: liquibase/liquibase:latest
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
      - ./src/main/resources/db/config/liquibase.properties:/liquibase/liquibase.properties
      - ./src/main/resources/db/config/mysql-connector-j-8.0.31.jar:/liquibase/internal/lib/mysql-connector-j-8.0.31.jar
    depends_on:
      - mysql
    command: tail -f /dev/null

  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: myuser
    ports:
      - '3306:3306'

volumes:
  java_ora_db_data: {}
